### ISSUE TITLE
 Why should we scale these value?

### ISSUE THREAD

**Issue by debugwangz** [YKZhangSEU/CLEAR#1]
![图片](https://user-images.githubusercontent.com/12813597/176696759-c8b63d8f-1458-42b6-ab1d-1b2cef62c653.png)
![图片](https://user-images.githubusercontent.com/12813597/176696937-abf73bfc-7f59-410b-993b-9baf9cfe0fa1.png)

**Comment by YKZhangSEU** [comment]
This is my personal habit. It's up to you.

发件人：debug ***@***.***>
发送日期：2022-06-30 22:02:51
收件人：YKZhangSEU/CLEAR ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[YKZhangSEU/CLEAR] Why should we scale these value? (Issue #1)
